///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.metrics.api.MetricsConfig
:keywords: helidon, config, io.helidon.metrics.api.MetricsConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.metrics.api.MetricsConfig
include::{rootdir}/includes/attributes.adoc[]

= MetricsConfig (metrics.api) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.metrics.api/io/helidon/metrics/api/MetricsConfig.html[io.helidon.metrics.api.MetricsConfig]


This is a standalone configuration type, prefix from configuration root: `metrics`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`app-name` |string |{nbsp} |Value for the application tag to be added to each meter ID.

 Application tag value
|`app-tag-name` |string |{nbsp} |Name for the application tag to be added to each meter ID.

 Application tag name
|`distribution.percentiles` |xref:{rootdir}/config/io_helidon_metrics_api_DistributionSetting_Percentiles.adoc[Percentiles[&#93;] |{nbsp} |Percentile settings of the form `meter-name-expression=percentile-values` where `meter-name-expression` is
 a name of a distribution summary or timer or a name prefix followed by a `*` suffix, and `percentile-values` is
 a possibly empty comma-separated list of decimal values in the closed interval `[0.0, 1.0]`. A builder for a
 distribution summary or timer which matches the `name-expression` is preloaded with the configured percentile values.
 If a builder's name matches multiple settings the last match wins.

     The string form of the configuration value can contain multiple occurrences of this format separated by semicolons.

 Example: `distribution.percentiles=alpha.*=0.5,0.75;alpha.summary=0.3,0.4` assigns percentile values 0.5 and 0.75
 to distribution summary or timer builders with names starting with `alpha.` and assigns values 0.3 and 0.4 to a
 builder with the exact meter name `alpha.summary`.

     Example: `distribution.percentiles=delta.summary=` suppresses percentiles for `delta.summary`.

     For any builder with a name that matches none of the settings the Helidon Micrometer-based metrics implementation
     preloads default percentile values of 0.5, 0.75, 0.95, 0.98, 0.99, 0.999.
 
 Percentile settings
|`distribution.summary.buckets` |xref:{rootdir}/config/io_helidon_metrics_api_DistributionSetting_SummaryBuckets.adoc[SummaryBuckets[&#93;] |{nbsp} |Non-timer distribution summary (histogram) bucket settings of the form `meter-name-expression=summary-bucket-values`
 where `meter-name-expression` is a name of a distribution summary or a name prefix followed by a `*` suffix,
 and `summary-bucket-values` is a possibly empty comma-separated list of decimal or integer numbers all greater than
 zero.
 A builder for a distribution summary which matches the `name-expression` is preloaded with the configured bucket
 boundary values.
 If a builder's name matches multiple settings the last match wins.

     The string form of the configuration value can contain multiple occurrences of this format separated by semicolons.

     Example: `distribution.summary.buckets=alpha.*=10.0,50.0,100.0;beta.summary1=30.0,50.0,123` assigns bucket
     values 10.0, 50.0, and 100.0 to builders with names starting with `alpha.`, and assigns bucket values
     30.0, 50.0, and 123.0 to any builder with the exact meter name `beta.summary1`.
 
 Non-timer distribution summary bucket settings
|`distribution.timer.buckets` |xref:{rootdir}/config/io_helidon_metrics_api_DistributionSetting_TimerBuckets.adoc[TimerBuckets[&#93;] |{nbsp} |Timer distribution summary (histogram) bucket settings of the form `meter-name-expression=timer-bucket-values` where
 `meter-name-expression` is a name of a timer or a name prefix followed by a `*` suffix, and
 `timer-bucket-values` is a possibly empty comma-separated list of integer values each followed by a time unit suffix:

- `ms` milliseconds (the default if no suffix appears after a value
- `s` seconds
- `m` minutes
- `h` hours

A builder for a timer which matches the `name-expression` is preloaded with the configured bucket boundary values.
 If a builder's name matches multiple settings the last match wins.

     The string form of the configuration value can contain multiple occurrences of this format separated by semicolons.

     Example: `distribution.timer.buckets=alpha.*=500ms,2s,3m;alpha.other=10s,2m,5h` assigns bucket values 500 ms,
     2 seconds, and 3 minutes to timer builders with names starting with `alpha.` and assigns values 10 seconds,
     2 minutes, and 5 hours to a timer builder with the exact meter name `alpha.other`.
 
 Timer distribution summary bucket settings
|`enabled` |boolean |`true` |Whether metrics functionality is enabled.

 If metrics are configured to be enabled
|[.line-through]#`gc-time-type`# |xref:{rootdir}/config/io_helidon_metrics_api_MetricsConfigBlueprint_GcTimeType.adoc[GcTimeType] |`GcTimeType.COUNTER` |*Deprecated* Whether the `gc.time` meter should be registered as a gauge (vs. a counter).
 The `gc.time` meter is inspired by the MicroProfile Metrics spec, in which the meter was originally checked to
 be a counter but starting in 5.1 was checked be a gauge. For the duration of Helidon 4.x users can choose which
 type of meter Helidon registers for `gc.time`.
 The type of meter to use for registering `gc.time`
 @deprecated Provided for backward compatibility only; no replacement
|`key-performance-indicators` |xref:{rootdir}/config/io_helidon_metrics_api_KeyPerformanceIndicatorMetricsConfig.adoc[KeyPerformanceIndicatorMetricsConfig] |{nbsp} |Key performance indicator metrics settings.

 Key performance indicator metrics settings
|`permit-all` |boolean |`true` |Whether to allow anybody to access the endpoint.

 Whether to permit access to metrics endpoint to anybody, defaults to `true`
 See roles()
|`rest-request-enabled` |boolean |`false` |Whether automatic REST request metrics should be measured.

 True/false
|`roles` |string[&#93; |`observe` |Hints for role names the user is expected to be in.

 List of hints
|`scoping` |xref:{rootdir}/config/io_helidon_metrics_api_ScopingConfig.adoc[ScopingConfig] |{nbsp} |Settings related to scoping management.

 Scoping settings
|`tags` |xref:{rootdir}/config/io_helidon_metrics_api_Tag.adoc[Tag[&#93;] |{nbsp} |Global tags.

 Name/value pairs for global tags

|===

// end::config[]