/*
 * Copyright (c) 2023 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.openapi;

import java.util.Map;

/**
 *
 * Wraps generated parser and uses {@link io.helidon.openapi.ExpandedTypeDescription} as its type.
 */
public abstract class ParserHelper {

    /**
     * The SnakeYAMLParserHelper is generated by a maven plug-in.
     */
    private final SnakeYAMLParserHelper<ExpandedTypeDescription> generatedHelper;

    /**
     * Creates a new instance of the parse helper.
     *
     * @param generatedHelper the SnakeYAML parser helper
     */
    protected ParserHelper(SnakeYAMLParserHelper<ExpandedTypeDescription> generatedHelper) {
        this.generatedHelper = generatedHelper;
        adjustTypeDescriptions(generatedHelper.types());
    }

    /**
     * Types.
     *
     * @return types of this helper
     */
    public Map<Class<?>, ExpandedTypeDescription> types() {
        return generatedHelper.types();
    }

    /**
     * Adjusts type descriptions as needed due to specific details of the model library.
     *
     * @param types the type-to-description map
     */
    protected abstract void adjustTypeDescriptions(Map<Class<?>, ExpandedTypeDescription> types);
}
